### ISSUE TITLE
Mapping of dynamic templates

### ISSUE THREAD

**Issue by arnordhaenens** [AviationCode/elasticsearch#61]
Currently it's only possible to configure base field mapping on an index. 

Advanced mapping using Dynamic templates ([https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html)) isn't currently possible when creating an index, this because of the following code in `src/Schema/Index.php`

```php
$this->elasticsearch->getClient()->indices()->putMapping([
    'index' => $this->getIndex($index),
    'body' => ['properties' => $mappings],
]);
```

To support dynamic templates, an extra (optional) key should be passed along to the body. I can create a PR for this, but I was wondering if you want this configuration to reside in a separate property on the model (eg: `$dynamicTemplatesMapping`) or to be added on the existing `$mapping` property. 

The last option will result in breaking changes, the first will be backwards compatible. 

Found the option of dynamic templates quite useful to limit duplication and re-use mapping of fields. 

Example: 
```php
public array $dynamicTemplatesMapping = [
    [
        'geo_location_template' => [
            'match_mapping_type' => 'object',
            'match_pattern' => 'regex',
            'match' => '^(street|city|country)$',
            'mapping' => [
                'type' => 'object',
                'properties' => [
                    'id' => ['type' => 'long'],
                    'name' => ['type' => 'keyword'],
                    'category' => ['type' => 'keyword'],
                    'external_id' => ['type' => 'keyword'],
                    'code' => ['type' => 'keyword'],
                ],
            ],
        ],
    ],
    [
        'nested_option_name' => [
            'match_mapping_type' => 'string',
            'path_match' => '*.options.*.name',
            'mapping' => ['type' => 'keyword'],
        ],
    ],
];
```

**Comment by Douglasdc3** [comment]
#62 fixes this issue (merged)
